=== bderidder/portal-foundation-classes/pfc-rt/src/main/resources/portal/services/service-configuration-1.0.dtd
<!-- PFC Service file-based configuration document.

<!DOCTYPE service PUBLIC 
	"-//PFC/PFC Service Configuration DTD 1.0//EN"
	"http://pfc.sourceforge.net/service-configuration-1.0.dtd">

An instance of this document contains the information required to 
instantiate and manage a service.

-->

<!ELEMENT service (name, controller, interfaces, attribute*, dependencies)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT value (#PCDATA)>

<!ELEMENT controller (#PCDATA)>

<!ELEMENT interfaces (interface*)>
<!ELEMENT interface (#PCDATA)>

<!ELEMENT attribute (name, value)>

<!ELEMENT dependencies (dependency*)>
<!ELEMENT dependency (#PCDATA)>

=== bderidder/portal-foundation-classes/pfc-demo/src/main/webapp/WEB-INF/services/Monitor-service.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE service PUBLIC
	"-//PFC/PFC Service Configuration DTD 1.0//EN"
	"http://pfc.sourceforge.net/service-configuration-1.0.dtd">

<service>

    <name>Monitor</name>

    <controller>portal.rt.services.monitor.MonitorServiceController</controller>

    <interfaces>
        <interface>portal.services.monitor.IMonitorService</interface>
    </interfaces>

    <attribute>
        <name>monitor.namespace</name>
        <value>put.your.namespace.here</value>
    </attribute>

    <dependencies/>

</service>

=== bderidder/portal-foundation-classes/pfc-rt/src/webapps/shared/WEB-INF/services/Registry-service.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE service PUBLIC 
	"-//PFC/PFC Service Configuration DTD 1.0//EN"
	"http://pfc.sourceforge.net/service-configuration-1.0.dtd">

<service>

	<name>Registry</name>

	<controller>portal.rt.services.registry.RegistryController</controller>
	
	<interfaces>
		<interface>portal.services.registry.IRegistry</interface>
	</interfaces>

	<attribute>
		<name>storage.filename</name>
		<value>/path/to/registry/file.xml</value>
	</attribute>
	
	<dependencies/>

</service>

=== bderidder/portal-foundation-classes/pfc-demo/src/main/webapp/WEB-INF/services/FreeMarker-service.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE service PUBLIC
	"-//PFC/PFC Service Configuration DTD 1.0//EN"
	"http://pfc.sourceforge.net/service-configuration-1.0.dtd">

<service>

	<name>FreeMarker Service</name>

	<controller>portal.rt.services.freemarker.FreeMarkerServiceController</controller>

	<interfaces>
		<interface>portal.services.freemarker.IFreeMarkerService</interface>
	</interfaces>

	<dependencies>
		<dependency>portal.services.registry.IRegistry</dependency>
		<dependency>portal.services.resource.IResourceService</dependency>
	</dependencies>

</service>

=== bderidder/portal-foundation-classes/pfc-demo/src/main/webapp/WEB-INF/services/Registry-service.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE service PUBLIC
	"-//PFC/PFC Service Configuration DTD 1.0//EN"
	"http://pfc.sourceforge.net/service-configuration-1.0.dtd">

<service>

    <name>Registry</name>

    <controller>portal.rt.services.registry.RegistryController</controller>

    <interfaces>
        <interface>portal.services.registry.IRegistry</interface>
    </interfaces>

    <attribute>
        <name>storage.filename</name>
        <value>/Users/bavo/NetBeansProjects/PFC-HEAD/trunk/pfc-demo/Demo-registry.xml</value>
    </attribute>

    <dependencies/>

</service>
